// <auto-generated />
namespace HotelFiesta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixCurrency2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCurrency2));
        
        string IMigrationMetadata.Id
        {
            get { return "202602270134405_FixCurrency2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
